[server]
headless = true

[client]
showErrorDetails = false

[theme]
primaryColor = "#0ea5e9"
backgroundColor = "#050b14"
secondaryBackgroundColor = "#0b1a30"
textColor = "#f1f5f9"
font = "sans serif"

[ui]
hideTopBar = true
